name: Py Spark Unit Tests


pool:
  vmImage: ubuntu-latest


stages:
- stage: Tests
  displayName: Unit Tests

  jobs:
    - job:
      displayName: PySpark Unit Tests
      steps:
          - script: |
              sudo apt-get update
              sudo apt-get install default-jdk -y
              pip install -r $(System.DefaultWorkingDirectory)/src/tests/test-requirements.txt
              cd src && python -m unittest -v
            displayName: Run Unit Tests